# config.yaml

path:
  img_pth: ./assets/image_data
  text_pth: ./assets/ocr_result(ocr+gpt)/
  output_ext: .txt

ocr:
  api: pororo # pororo, easy, tesseract, paddle is avilable
  pororo:
    lang: ko
  easy:
    lang: ['ko', 'en']
    GPU: False
  tesseract:
    lang: kor
  paddle:
    lang: korean

gpt_params:
  api_key: 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 # should be deleted
  engine: text-davinci-003
  max_tokens: 1500

gpt_prompt:
  prompt : 
    '''

    Above text data is korean food information label that is not parsed. 
    Also partial correction is needed.
    Parse and correct given text data as possible as you can.
    Most of the word should be related with food.
    text data should be in Korean
    '''

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .