# config.yaml

path:
  img_pth: ./assets/image_data/data (2)
  text_pth: ./assets/ocr_result(ocr+gpt)/data/ # need '/' at last
  output_ext: .txt

ocr:
  api: pororo # pororo, easy, tesseract, paddle is avilable
  pororo:
    lang: ko
  easy:
    lang: ['ko', 'en']
    GPU: False
  tesseract:
    lang: kor
  paddle:
    lang: korean

gpt_params:
  api_key: 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 # should be deleted
  engine: text-davinci-003
  max_tokens: 1500

gpt_prompt:
  prompt : 
    '''
    Given the text extracted from an OCR process of a Korean food label, perform the following tasks:
    Parse the text and correct any errors or inconsistencies.
    Align the text for proper organization and readability.
    Translate the text into Korean, ensuring that the words pertain to food.
    Document the processed data with appropriate formatting, including indentation and line breaks.
    Please make sure that the final output is in Korean while maintaining the accuracy and integrity of the original information.
    '''

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .