# config.yaml

path:
  img_pth: ./assets/image_data
  text_pth: ./assets/ocr_result(ocr+gpt)/
  output_ext: .txt

ocr:
  api: pororo # pororo, easy, tesseract, paddle is avilable
  pororo:
    lang: ko
  easy:
    lang: ['ko', 'en']
    GPU: False
  tesseract:
    lang: kor
  paddle:
    lang: korean

gpt_params:
  api_key: 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 # should be deleted
  engine: text-davinci-003
  max_tokens: 1500

gpt_prompt:
  prompt : 
    '''
    Parse, correct, align, translate, and document this unparsed Korean food label data.
    Ensure the words pertain to food, use common sense for awkward word corrections.
    The final output should be in Korean.
    '''

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .